environments:
  pypi_package:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - docker-jupyterhub
pipelines:
  docker-jupyterhub:
    group: pypi_package
    locking: off
    materials:
      docker-jupyterhub_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/docker-jupyterhub.git
        branch: master
        destination: docker-jupyterhub
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: docker-jupyterhub
      TEST_DIRECTORY: docker-jupyterhub
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package