environments:
  docker_image:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - docker-jupyterhub
pipelines:
  docker-jupyterhub:
    group: docker_image
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      docker-jupyterhub_git:  # this is the name of material
        # says about type of material and url at once
        name: docker-jupyterhub
        git: https://github.com/ucphhpc/docker-jupyterhub.git
        branch: master
        destination: docker-jupyterhub
      publish_docker_git:  # this is the name of material
        # says about type of material and url at once
        name: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-docker-scripts
    parameters:
      IMAGE: docker-jupyterhub
      ARGS: ''
      DEFAULT_TAG: latest
      COMMIT_TAG: GO_REVISION_DOCKER_JUPYTERHUB_GIT
      EXTRA_TAG: 3.1.1
      SRC_DIRECTORY: docker-jupyterhub
      TEST_DIRECTORY: docker-jupyterhub
      PUSH_DIRECTORY: publish-docker-scripts
    template: docker_image
