version: '3.7'

services:
  jupyterhub:
    image: nielsbohr/jupyterhub:latest
    container_name: jupyterhub
    ports:
      - "80:8000/tcp"
    volumes:
      - ./hub/jupyterhub_config_access_service.py:/srv/jupyterhub/jupyter_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: jupyterhub -f /srv/jupyterhub/jupyter_config.py

networks:
  default:
    name: jupyterhub_default
    driver: overlay
