services:
  jupyterhub:
    image: ucphhpc/jupyterhub:$TAG
    build:
      context: ./hub
      dockerfile: Dockerfile
    container_name: jupyterhub
    ports:
      - "80:8000/tcp"
    env_file:
      - .env
    volumes:
      - ./hub/jupyterhub_config.py:/srv/jupyterhub/jupyter_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: jupyterhub -f /srv/jupyterhub/jupyter_config.py

networks:
  default:
    name: jupyterhub_default
    driver: bridge